language: python
sudo: false
branches:
  only:
  - master

matrix:
  include:
    - python: 2.7
      env: id=latest TOXENV=py27-twisted-latest
    - python: 2.7
      env: id=p27-recent TOXENV=py27-twisted-17,py27-twisted-16,py27-twisted-15,py27-twisted-14
    - python: 2.7
      env: id=p27-older TOXENV=py27-twisted-13,py27-twisted-12,py27-twisted-11,py27-twisted-10
    - python: 2.7
      env: id=p27-tornado TOXENV=py27-tornado
    - python: "pypy-5.3.1"
      env: id=pypy-tornado TOXENV=pypy-tornado

    # todo: fix asyncore, or deprecate
    #- env: id=py27-asyncore TOXENV=py27-asyncore

cache:
  - apt

addons:
  apt:
    packages:
      - libssl-dev

install:
  - pip install tox

script:
  - tox
