language: python
sudo: false
branches:
  only:
  - master

matrix:
  include:
    - env: id=latest TOXENV=py27-twisted-latest
    - env: id=p27-recent TOXENV=py27-twisted-16,py27-twisted-15,py27-twisted-14
    - env: id=p27-older TOXENV=py27-twisted-13,py27-twisted-12,py27-twisted-11,py27-twisted-10
    - env: id=p26 TOXENV=py26-twisted-13,py26-twisted-12,py26-twisted-11,py26-twisted-10
    - env: id=tornado TOXENV=py27-tornado,pypy-tornado
      python: "pypy-5.3.1"
    # todo: fix asyncore, or deprecate
    #- env: id=py27-asyncore TOXENV=py27-asyncore
    #- env: id=py26-asyncore TOXENV=py26-asyncore

cache:
  - apt

addons:
  apt:
    packages:
      - libssl-dev

install:
  - pip install tox

script:
  - tox
